### ISSUE TITLE
Values are now encrypted

### ISSUE THREAD

**Issue by mengwong** [briandfoy/http-cookies-chrome#1]
At some point, we shall have to heroically update the code with AES decryption. The method is shown here:

http://n8henrie.com/2014/05/decrypt-chrome-cookies-with-python/

I had a go but couldn't quite make it work. Sorry this is an issue not a pull request.

**Comment by briandfoy** [comment]
Heh, this issue is really old, and that's probably the last time I used Chrome.

The latest sources in the repo have the start of this fix. The module can read the encrypted cookies and load them into the data structure. I haven't done the bit to write them back out though.

**Comment by briandfoy** [comment]
I've uploaded 2.001. There are probably still a few issues, but if you run into something, open a new issue.
