### ISSUE TITLE
DBD::SQLite::db prepare failed with latest chrome

### ISSUE THREAD

**Issue by cougarhead** [briandfoy/http-cookies-chrome#3]
DBD::SQLite::db prepare failed: malformed database schema (is_transient) - near "where": syntax error at /Library/Perl/5.18/HTTP/Cookies/Chrome.pm line 99.
Can't call method "execute" on an undefined value at /Library/Perl/5.18/HTTP/Cookies/Chrome.pm line 101.

my chrome version is "Version 65.0.3325.181 (Official Build) (64-bit)"
perl version is "(v5.18.2) on mac"

**Comment by briandfoy** [comment]
Closing this in favor of #1, which I think is the same issue.
